version: '3.7'

services:
  blog:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/app/Blog/static
      - .:/app/
    expose:
      - 8000
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/Blog/static
    ports:
      - 1337:80
    depends_on:
      - blog
volumes:
  static_volume: