kind: Service
apiVersion: v1
metadata:
  name: gmjnow-service
spec:
  type: ClusterIP
  selector:
    app: gmjnow-container
  ports:
  - protocol: TCP
    targetPort: 8000
    port: 8000
    nodePort: 30080
  type: NodePort